---
title: "First Knit"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended high-school and graduated high-school from Edwards Air Force Base, Desert-Junior Senior High in California. I prefer English over math, just because I understand it better. Math I find it to be a little more complicated, especially word problems for me can be tough. I did best in Art and Science class, art was mainly an elective but my strongest class knowledge wise is science.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I believe mine is widnows. I would be at a 7, I am confident with comupters if I know what I am doing. My internet access is pretty good and fast.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called Ashley, so my normal name.
   
 

## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to be successful in anything that I do. I want to get a degree in medical assistant, then find a good paying job at a hospital or a clinic. My degree is for a Medical Assistant, this is my 3rd year at AVC.
 


## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
No I have never been to forighn countires. I went on a cruise one time that took me to the Bahamas and St. Marten but that was it when it comes to leaving the country even though those are islands. My dad was in the military for a couple of years, but I personally will never go into the force of any kind. 
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




